#!/bin/bash

protected_branch='main'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]
then
    echo "You are pushing to the main branch, please move your changes to another branch, then pull request to merge with main."
    exit 1 # push will execute
else
    exit 0 # push will execute
fi
